function pendingKey(){return 'altitudProduccionCampo'}
function syncLockKey(){return 'altitudProduccionSyncing'}
function loadPending(){try{return JSON.parse(localStorage.getItem(pendingKey())||'[]')}catch(err){return[]}}
function savePending(rows){localStorage.setItem(pendingKey(),JSON.stringify(dedupeProduccion((rows||[]).filter(row=>row.pending))))}
function validProduccion(rows){return(rows||[]).filter(r=>text(r.fecha)||text(r.variedad)||asNumber(r.tallos_cortados))}
function recordId(row){return text(row.id_produccion)||[row.fecha,row.semana,row.siembra||row.bloque,row.cama,row.variedad,row.tallos_cortados,row.responsable].map(text).join('|')}
function dedupeProduccion(rows){const map=new Map();validProduccion(rows).forEach(row=>{const id=recordId(row);if(!id)return;const existing=map.get(id);if(!existing||(!existing.pending&&row.pending===false)||text(row.creado_en)>text(existing.creado_en)){map.set(id,row)}});return Array.from(map.values()).sort((a,b)=>text(b.creado_en).localeCompare(text(a.creado_en))||text(b.fecha).localeCompare(text(a.fecha)))}
function rowStatus(row){if(row.pending)return '<span class="pill warn">LOCAL</span>';return `<span class="pill ok">${text(row.estado||'REGISTRADO')}</span>`}
function deleteButton(row){return `<button class="btn danger small" type="button" data-delete-produccion="${recordId(row)}">Eliminar</button>`}
function renderProduccion(rows){rows=dedupeProduccion(rows).filter(row=>text(row.estado).toUpperCase()!=='ELIMINADO');renderRows($('produccionBody'),rows,[r=>r.fecha,r=>r.semana,r=>r.siembra||r.bloque,r=>r.cama,r=>r.variedad,r=>fmtInt(r.tallos_cortados),r=>r.responsable,r=>rowStatus(r),r=>deleteButton(r)]);$('kRegistros').textContent=fmtInt(rows.length);$('kTallos').textContent=fmtInt(rows.reduce((a,r)=>a+asNumber(r.tallos_cortados),0))}
function isoWeek(dateText){const d=new Date(`${dateText}T00:00:00`);if(Number.isNaN(d.getTime()))return'';d.setDate(d.getDate()+4-(d.getDay()||7));const yearStart=new Date(d.getFullYear(),0,1);return Math.ceil((((d-yearStart)/86400000)+1)/7)}
function setupProduccionForm(){if($('variedad'))$('variedad').innerHTML='<option value="">Selecciona variedad</option>'+ALTITUD.variedades.map(v=>`<option value="${v}">${v}</option>`).join('');const updateWeek=()=>{$('semana').value=isoWeek($('fecha').value)};$('fecha')?.addEventListener('change',updateWeek);$('fecha').value=$('fecha').value||todayISO();updateWeek()}
async function deleteRecord(sheetName,idField,idValue){if(!ALTITUD.appsScriptUrl)throw new Error('Apps Script no configurado');const user=window.ALTITUD_PERMISOS?ALTITUD_PERMISOS.getCurrentUser():{};await fetch(ALTITUD.appsScriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'deleteRecord',sheet:sheetName,idField,idValue,user})})}
async function syncPendingProduccion(rows){let pending=dedupeProduccion(loadPending());if(!pending.length||!ALTITUD.appsScriptUrl)return rows;const lockUntil=Number(localStorage.getItem(syncLockKey())||0);if(Date.now()<lockUntil)return rows;localStorage.setItem(syncLockKey(),String(Date.now()+15000));setStatus(`Sincronizando ${pending.length} registros locales...`);const remaining=[];for(const row of pending){try{const clean={...row};delete clean.pending;await submitRecord(ALTITUD.sheets.produccion,clean)}catch(err){remaining.push(row)}}savePending(remaining);localStorage.removeItem(syncLockKey());if(remaining.length){setStatus(`${remaining.length} registros siguen pendientes de sincronizar`)}else{setStatus('Registros locales sincronizados en Sheets')}return dedupeProduccion(rows.map(row=>row.pending&&!remaining.some(p=>recordId(p)===recordId(row))?{...row,pending:false,estado:'REGISTRADO'}:row))}
async function initProduccion(){let rows=loadPending();try{rows=dedupeProduccion([...(await loadSheet(ALTITUD.sheets.produccion)),...rows])}catch(err){rows=dedupeProduccion(rows)}rows=await syncPendingProduccion(rows);renderProduccion(rows);setStatus(ALTITUD.appsScriptUrl?`Produccion campo - ${dedupeProduccion(rows).length} registros`:`Produccion campo - falta configurar Apps Script para subir a Sheets`);setupProduccionForm();$('produccionBody')?.addEventListener('click',async e=>{const button=e.target.closest('[data-delete-produccion]');if(!button)return;const id=button.dataset.deleteProduccion;if(!confirm('Eliminar este registro de produccion?'))return;rows=rows.filter(row=>recordId(row)!==id);savePending(loadPending().filter(row=>recordId(row)!==id));renderProduccion(rows);setStatus('Eliminando registro...');try{await deleteRecord(ALTITUD.sheets.produccion,'id_produccion',id);setStatus('Registro eliminado. Si estaba en Sheets, se quitara al actualizar.')}catch(err){setStatus('Registro eliminado localmente; no se pudo conectar con Sheets')}});$('prodForm').addEventListener('submit',async e=>{e.preventDefault();const fecha=$('fecha').value;const record={id_produccion:`P-${Date.now()}`,fecha,semana:isoWeek(fecha),siembra:text($('siembra').value),cama:text($('cama').value),variedad:text($('variedad').value).toUpperCase(),tallos_cortados:asNumber($('tallos').value),responsable:text($('responsable').value),estado:'REGISTRADO',observaciones:text($('observaciones').value),creado_en:new Date().toISOString(),origen:'WEB'};rows=dedupeProduccion([record,...rows]);renderProduccion(rows);try{await submitRecord(ALTITUD.sheets.produccion,record);setStatus('Produccion guardada en Google Sheets')}catch(err){const pendingRecord={...record,pending:true};rows=rows.map(row=>recordId(row)===recordId(record)?pendingRecord:row);savePending([...loadPending(),pendingRecord]);renderProduccion(rows);setStatus('Produccion guardada localmente; se sincronizara cuando Apps Script responda')}})}
document.addEventListener('DOMContentLoaded',initProduccion);
