let processedRows=[],salesRows=[],stockRows=[],stockData=null;
function loginOk(){return sessionStorage.getItem('altitudSellerAccess')==='1'}
function showApp(){if($('loginView'))$('loginView').style.display='none';if($('appView'))$('appView').style.display='block'}
function saleId(row){return text(row.id_venta)||[row.fecha,row.vendedor,row.cliente,row.variedad,row.medida_cm,row.tallos,row.total_venta].map(text).join('|')}
function renderSalesDetail(){const rows=normalizeSales(salesRows).filter(r=>ALTITUD.variedades.includes(r.variedad)).slice().sort((a,b)=>text(b.creado_en).localeCompare(text(a.creado_en))||text(b.fecha).localeCompare(text(a.fecha)));renderRows($('salesBody'),rows,[r=>r.fecha,r=>r.vendedor,r=>r.cliente,r=>r.variedad,r=>medidaLabel(r.medida_cm),r=>fmtInt(r.tallos),r=>fmtMoney(r.total_venta||r.tallos*r.precio_unitario),r=>`<span class="pill ${r.pending?'warn':'ok'}">${r.pending?'LOCAL':r.estado}</span>`,r=>`<button class="btn danger small" type="button" data-delete-sale="${saleId(r)}">Eliminar</button>`])}
function currentStock(variedad,medida){return getStockForSale(stockData,variedad,medida).stockDisponible||0}
function activeMeasureRows(){return(stockData?.porVariedadMedida||[]).filter(r=>ALTITUD.variedades.includes(r.variedad))}
function fillSaleSelects(){const rows=activeMeasureRows().filter(r=>r.stockDisponible>0);const varieties=ALTITUD.variedades.filter(v=>rows.some(r=>r.variedad===v));$('saleVariedad').innerHTML=varieties.length?varieties.map(v=>`<option value="${v}">${v}</option>`).join(''):ALTITUD.variedades.map(v=>`<option value="${v}">${v}</option>`).join('');updateMeasureOptions()}
function saleTipoMedidas(){return text($('saleTipo')?.value).toUpperCase()==='NACIONAL'?['NACIONAL']:['70','60','55','50']}
function updateMeasureOptions(){const variedad=$('saleVariedad').value;const selected=normalizarMedida($('saleMedida')?.value);const measures=saleTipoMedidas();$('saleMedida').innerHTML=measures.map(m=>{const row=getStockForSale(stockData,variedad,m);const disabled=row.stockDisponible<=0?' disabled':'';return`<option value="${m}"${disabled}>${medidaLabel(m)} - ${fmtInt(row.stockDisponible)}</option>`}).join('');if(measures.includes(selected))$('saleMedida').value=selected}
function syncTallosFromBunches(){const bunches=asNumber($('saleBunches').value);if(bunches>0)$('saleTallos').value=bunches*(ALTITUD.tallosPorBunch||10)}
function stockMessage(variedad,medida,tallos){const row=getStockForSale(stockData,variedad,medida);const other=otherMeasureSuggestions(stockData,variedad,medida);if(row.stockDisponible<=0){return other.length?`La medida seleccionada esta agotada. Existe stock disponible en otras medidas: ${other.map(r=>medidaLabel(r.medida)).join(', ')}.`:'La medida seleccionada esta agotada.'}if(tallos>row.stockDisponible){return other.length?`No hay stock suficiente para esta variedad y medida. Existe stock disponible en otras medidas: ${other.map(r=>medidaLabel(r.medida)).join(', ')}.`:'No hay stock suficiente para esta variedad y medida.'}return'Listo para registrar una venta.'}
function updatePreview(){const variedad=$('saleVariedad').value,medida=$('saleMedida').value,tallos=asNumber($('saleTallos').value),precio=asNumber($('salePrecio').value),disponible=currentStock(variedad,medida);$('saleDisponible').textContent=fmtInt(disponible);$('saleTotal').textContent=fmtMoney(tallos*precio);const msg=$('saleMessage');msg.textContent=stockMessage(variedad,medida,tallos);msg.style.color=(tallos>disponible||disponible<=0)?'#8d2929':'var(--muted)'}
function renderVendedores(){stockData=calculateColdRoomStock(processedRows,salesRows);stockRows=stockData.porVariedadMedida;const visibleRows=activeMeasureRows();const totalStock=stockData.resumen.stockDisponible,vendido=stockData.resumen.vendido,ingresos=normalizeSales(salesRows).filter(r=>ALTITUD.variedades.includes(r.variedad)).reduce((a,r)=>a+(r.total_venta||r.tallos*r.precio_unitario),0);$('kStock').textContent=fmtInt(totalStock);$('kVendido').textContent=fmtInt(vendido);$('kIngresos').textContent=fmtMoney(ingresos);$('kVariedades').textContent=fmtInt(stockData.resumen.variedadesDisponibles);renderRows($('availabilityBody'),visibleRows,[r=>r.variedad,r=>medidaLabel(r.medida),r=>fmtInt(r.procesadoUtil),r=>fmtInt(r.vendido),r=>fmtInt(r.stockDisponible),r=>`<span class="pill ${r.estado==='AGOTADO'||r.estado==='INCONSISTENCIA'?'bad':r.estado==='BAJO STOCK'?'warn':'ok'}">${r.estado}</span>`]);fillSaleSelects();updatePreview();renderSalesDetail()}
async function loadVendedores(){setStatus('Cargando ventas...');const data=await loadProcessedAndSales();processedRows=data.processed;salesRows=data.sales;renderVendedores();setStatus(`En linea - ${processedRows.length} registros de poscosecha`)}
function buildSaleRecord(){syncTallosFromBunches();const now=new Date(),bunches=asNumber($('saleBunches').value),tallos=asNumber($('saleTallos').value),precio=asNumber($('salePrecio').value),tipo=text($('saleTipo').value).toUpperCase(),medida=tipo==='NACIONAL'?'NACIONAL':normalizarMedida($('saleMedida').value);return{id_venta:`V-${Date.now()}`,fecha:todayISO(),hora:now.toTimeString().slice(0,5),vendedor:text($('saleVendedor').value),cliente:text($('saleCliente').value),variedad:text($('saleVariedad').value).toUpperCase(),medida_cm:medida,tipo,bunches,tallos,precio_unitario:precio,total_venta:tallos*precio,estado:'VENDIDO',observaciones:text($('saleObs').value),creado_en:now.toISOString(),origen:'WEB',pending:true}}
async function initVendedores(){if($('loginForm'))$('loginForm').addEventListener('submit',e=>{e.preventDefault();const user=text($('user').value).toUpperCase(),pin=text($('pin').value);if(ALTITUD.sellerUsers[user]===pin){sessionStorage.setItem('altitudSellerAccess','1');showApp();loadVendedores()}else $('loginError').style.display='block'});if(loginOk()){showApp();loadVendedores()}$('logoutBtn')?.addEventListener('click',()=>{sessionStorage.removeItem('altitudSellerAccess');location.reload()});$('refreshBtn')?.addEventListener('click',loadVendedores);$('saleVariedad')?.addEventListener('change',()=>{updateMeasureOptions();updatePreview()});$('saleMedida')?.addEventListener('change',updatePreview);$('saleTipo')?.addEventListener('change',()=>{updateMeasureOptions();updatePreview()});['saleTallos','salePrecio'].forEach(id=>$(id)?.addEventListener('input',updatePreview));$('saleBunches')?.addEventListener('input',()=>{syncTallosFromBunches();updatePreview()});$('salesBody')?.addEventListener('click',async e=>{const button=e.target.closest('[data-delete-sale]');if(!button)return;const id=button.dataset.deleteSale;if(!confirm('Eliminar esta venta? El stock volvera a estar disponible.'))return;salesRows=salesRows.filter(row=>saleId(row)!==id);savePendingSales(salesRows);renderVendedores();const msg=$('saleMessage');msg.textContent='Eliminando venta...';try{await deleteSheetRecord(ALTITUD.sheets.ventas,'id_venta',id);msg.textContent='Venta eliminada y stock actualizado.'}catch(err){msg.textContent='Venta eliminada localmente; no se pudo conectar con Sheets.'}msg.style.color='var(--green-800)'});$('saleForm')?.addEventListener('submit',async e=>{e.preventDefault();const record=buildSaleRecord(),row=getStockForSale(stockData,record.variedad,record.medida_cm),msg=$('saleMessage');if(!record.vendedor||!record.cliente||!record.tallos){msg.textContent='Completa vendedor, cliente y tallos.';msg.style.color='#8d2929';return}if(row.stockDisponible<=0){msg.textContent=stockMessage(record.variedad,record.medida_cm,record.tallos);msg.style.color='#8d2929';return}if(record.tallos>row.stockDisponible){msg.textContent=stockMessage(record.variedad,record.medida_cm,record.tallos);msg.style.color='#8d2929';return}salesRows.push(record);savePendingSales(salesRows);renderVendedores();$('saleForm').reset();updateMeasureOptions();try{await submitRecord(ALTITUD.sheets.ventas,record);record.pending=false;savePendingSales(salesRows);msg.textContent='Venta guardada en Sheets y stock actualizado.'}catch(err){msg.textContent='Venta registrada en pantalla. Falta publicar Apps Script para guardar en Sheets.'}msg.style.color='var(--green-800)'})}
document.addEventListener('DOMContentLoaded',initVendedores);
